# Generated by Django 4.2.2 on 2023-12-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratinghistory',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
